/**
 * Modulo: frontend/scripts
 * Arquivo: generate_wiki_meta.cjs
 * Funcao no sistema: gerar metadados do Wiki (data/hora de ultima atualizacao) para exibicao na UI.
 *
 * Observacao:
 * - Quando o repositorio Git estiver disponivel, usa `git log -1` por arquivo (data do ultimo commit).
 * - Em ambientes sem `.git` (ex.: build em container), faz fallback para `mtime` do arquivo.
 * - Saida: `frontend/src/wiki/wikiMeta.generated.js` (importado pela UI).
 */

/* eslint-disable no-console */
const fs = require("node:fs");
const path = require("node:path");
const cp = require("node:child_process");

const repoRoot = path.resolve(__dirname, "..", "..");
const wikiDir = path.resolve(__dirname, "..", "src", "wiki");
const outFile = path.resolve(wikiDir, "wikiMeta.generated.js");
const gitDir = path.resolve(repoRoot, ".git");

const PAGES = [
  { id: "indice", filename: "00_indice.md" },
  { id: "visao-geral", filename: "01_visao_geral.md" },
  { id: "perfis", filename: "02_perfis_acesso.md" },
  { id: "consulta-bens", filename: "03_consulta_bens.md" },
  { id: "importacao-geafin", filename: "04_importacao_geafin.md" },
  { id: "movimentacoes", filename: "05_movimentacoes.md" },
  { id: "inventario", filename: "06_inventario_sala_a_sala.md" },
  { id: "intrusos-terceiros", filename: "07_intrusos_bens_de_terceiros.md" },
  { id: "wizard-art141", filename: "08_wizard_art141.md" },
  { id: "relatorios-auditoria", filename: "09_relatorios_auditoria.md" },
  { id: "troubleshooting", filename: "10_solucao_problemas.md" },
  { id: "glossario", filename: "11_glossario.md" },
  { id: "seguranca", filename: "12_politica_seguranca.md" },
  { id: "compliance", filename: "13_compliance_atn303.md" },
  { id: "admin-vps", filename: "14_admin_operacao_vps.md" },
  { id: "api-ref", filename: "15_referencia_api.md" },
  { id: "matriz-compliance", filename: "16_matriz_compliance.md" },
  { id: "regularizacao", filename: "17_regularizacao_pos_inventario.md" },
  { id: "checklist-migracoes", filename: "18_checklist_migracoes.md" },
];

function toGitPath(p) {
  return String(p).replace(/\\/g, "/");
}

function tryGitLastCommitIso(absFile) {
  const rel = toGitPath(path.relative(repoRoot, absFile));
  try {
    const out = cp.execFileSync("git", ["log", "-1", "--format=%cI", "--", rel], {
      cwd: repoRoot,
      stdio: ["ignore", "pipe", "ignore"],
      encoding: "utf8",
    });
    const iso = String(out || "").trim();
    return iso || null;
  } catch {
    return null;
  }
}

function fileMtimeIso(absFile) {
  const st = fs.statSync(absFile);
  return st.mtime.toISOString();
}

function generate() {
  // Important: in container builds the frontend folder is copied without the repo `.git` directory.
  // In that scenario, using `mtime` would make every page look "updated" at build time, which is misleading.
  // So: if `.git` is not available AND we already have a generated file, keep it unchanged.
  // This preserves the Git-based timestamps generated during development/release packaging.
  const hasGit = fs.existsSync(gitDir);
  if (!hasGit && fs.existsSync(outFile)) {
    console.log(
      `[wiki-meta] skip: .git not found at ${path.relative(process.cwd(), gitDir)}; keeping existing ${path.relative(
        repoRoot,
        outFile
      )}`
    );
    return;
  }

  const meta = {};
  for (const p of PAGES) {
    const abs = path.resolve(wikiDir, p.filename);
    const isoGit = tryGitLastCommitIso(abs);
    const iso = isoGit || fileMtimeIso(abs);
    meta[p.id] = { updatedAt: iso, source: isoGit ? "git" : "mtime" };
  }

  const generatedAt = new Date().toISOString();
  const body =
    `// This file is auto-generated by frontend/scripts/generate_wiki_meta.cjs\n` +
    `// Do not edit manually.\n` +
    `export const wikiMetaGeneratedAt = ${JSON.stringify(generatedAt)};\n` +
    `export const wikiMeta = ${JSON.stringify(meta, null, 2)};\n`;

  fs.writeFileSync(outFile, body, "utf8");
  console.log(`[wiki-meta] wrote ${path.relative(repoRoot, outFile)} at ${generatedAt}`);
}

generate();
